### ISSUE TITLE
route seems to be broken

### ISSUE THREAD

**Issue by bkrrr** [whitecolor/watchalive#5]
I have this file structure:
...
watchalive.js
-/node_modules/
-/src/
--index.html

and this route defined:
```
 route: [
          {'/': '/src/index.html'}
    ]
```

i can call from my browser:
localhost:8080/src/index.html
but i **can't** call 
localhost:8080/

consol output:
DEBUG MODE ACTIVE
[ExpressApp] Proxy requests /api/* to http://www.test.de
[ExpressApp] Serve static on /Users/name/Documents/workspace/repository/trunk/webclient
[ExpressApp] Route / /src/index.html
[STDIN MANAGE] Press ENTER to output available commands
[ExpressApp] Watchalive HTTP server listening on port 8081
[ExpressApp] New client session client_1456603365877
route match / /src/index.html /

is this a bug or am i wrong with something?

regards Beny

**Comment by whitecolor** [comment]
You can enable debug mode (`debug: true`) to get more output.
