### ISSUE TITLE
proxy function seems to be broken

### ISSUE THREAD

**Issue by bkrrr** [whitecolor/watchalive#6]
I have this file structure:
...
watchalive.js
-/node_modules/
-/src/
--index.html

and this route defined:
 ```
proxy: {
        '/api': 'http://services.odata.org/V3/(S(1fa5xyez311tql34zcs2gqo0))/OData/OData.svc',
    }
```
i can call from my browser:

localhost:8080/api => not found
console:
[WatchStore] Could not read file /Users/bkr/Documents/workspace/repository/trunk/webclient/api 
expected the same result as if i call the url direct

localhost:8080/api/Products => is callling  http://services.odata.org/V3/(S(1fa5xyez311tql34zcs2gqo0))/OData/OData.svc/**api**/Products
obviously wrong. 

expected is
http://services.odata.org/V3/(S(1fa5xyez311tql34zcs2gqo0))/OData/OData.svc/Products

regards Beny

**Comment by whitecolor** [comment]
By default proxy config is context based
```js
proxy: {
        '/api': 'http://services.odata.org',
    }
```
so you do local request
`api/Products` will send it to 'http://services.odata.org/api/Poducts'

**Comment by bkrrr** [comment]
oh thank you, i haven't thought about that.
Could be helpful to be explicit documented.

**Comment by whitecolor** [comment]
Yes, docs are not explicit at this point)
